version: '3.8'

services:
  node:
    container_name: agrocybernetyka-node
    build:
      context: .docker/node
    ports:
      - "80:80"
      - "3000:3000"
    volumes:
      - ./:/app
    networks:
      agrocybernetyka-network:
        ipv4_address: 10.10.69.2
    stdin_open: true 
    tty: true
    command: tail -f /dev/null

networks:
  agrocybernetyka-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.69.0/24
